from selenium import webdriver
driver= webdriver.Chrome()
driver.implicitly_wait(10)
driver.get("https://demo.opencart.com/")

driver.find_element_by_xpath("//div/ul/li/a[@title='My Account']").click()
driver.find_element_by_xpath("//div/ul/li/ul/li/a[@href='https://demo.opencart.com/index.php?route=account/login']").click()
driver.find_element_by_xpath("//div/input[@name='email']").send_keys("jeevprabnivash@gmail.com")
driver.find_element_by_xpath("//div/input[@name='password']").send_keys("1234")
driver.find_element_by_xpath("//div/form/input[@type='submit']").click()
driver.find_element_by_xpath("//div/ul/li/a[@href='https://demo.opencart.com/index.php?route=account/address']").click()
driver.find_element_by_xpath("//div/a[@href='https://demo.opencart.com/index.php?route=account/address/add']").click()
driver.find_element_by_xpath("//div/input[@name='firstname']").send_keys("Nivash")
driver.find_element_by_xpath("//div/input[@name='lastname']").send_keys("J P")
driver.find_element_by_xpath("//div/input[@name='address_1']").send_keys("pillaiyar kovil street")
driver.find_element_by_xpath("//div/input[@name='city']").send_keys("Vellore")
driver.find_element_by_xpath("//div/input[@name='postcode']").send_keys("12341234")
driver.find_element_by_xpath("//div/select[@name='country_id']/option[@value='99']").click()
driver.find_element_by_xpath("//div/select[@name='zone_id']/option[@value='1503']").click()
driver.find_element_by_xpath("//div/label/input[@name='default']").click()
driver.find_element_by_xpath("//div/input[@type='submit']").click()
